/**
 * Centralized route utilities for workspace-aware URL generation.
 * All dashboard routes should use these functions to ensure workspace is included in URLs.
 * 
 * NOTE: Routes are now organized in separate modules under @/lib/routes/
 * This file re-exports everything for backward compatibility.
 */

// Re-export from modular route files
export { STATIC_ROUTES } from './routes/static.routes';
export { DASHBOARD_ROUTES, createWorkspaceRoutes } from './routes/dashboard.routes';
export { DOCS_ROUTES } from './routes/docs.routes';
export { extractWorkspaceFromPath, isDashboardPath, isDocsPath } from './routes/utils';

// Legacy ROUTES object for backward compatibility
// Maps old route names to new modular structure
import { STATIC_ROUTES } from './routes/static.routes';
import { DASHBOARD_ROUTES } from './routes/dashboard.routes';

export const ROUTES = {
  // Public routes (no workspace needed)
  HOME: STATIC_ROUTES.HOME,
  LOGIN: STATIC_ROUTES.LOGIN,
  REGISTER: STATIC_ROUTES.REGISTER,
  FORGOT_PASSWORD: STATIC_ROUTES.FORGOT_PASSWORD,
  RESET_PASSWORD: STATIC_ROUTES.RESET_PASSWORD,
  DOCS: '/docs',
  WORKSPACE_SELECTION: STATIC_ROUTES.WORKSPACE_SELECTION,

  // Dashboard base (requires workspace)
  DASHBOARD: DASHBOARD_ROUTES.DASHBOARD,
  
  // Project routes
  PROJECTS: DASHBOARD_ROUTES.PROJECTS,
  PROJECT_NEW: DASHBOARD_ROUTES.PROJECT_NEW,
  PROJECT_IMPORT: DASHBOARD_ROUTES.PROJECT_IMPORT,
  PROJECT_SELECT_REPO: DASHBOARD_ROUTES.PROJECT_SELECT_REPO,
  PROJECT_DETAIL: DASHBOARD_ROUTES.PROJECT_DETAIL,
  PROJECT_SETUP: DASHBOARD_ROUTES.PROJECT_SETUP,
  PROJECT_SETUP_SUCCESS: DASHBOARD_ROUTES.PROJECT_SETUP_SUCCESS,
  PROJECT_SETTINGS: DASHBOARD_ROUTES.PROJECT_SETTINGS,
  
  // Branch/Issue routes
  BRANCH_ISSUES: DASHBOARD_ROUTES.BRANCH_ISSUES,
  ISSUE_DETAIL: DASHBOARD_ROUTES.ISSUE_DETAIL,
  
  // Job routes
  PROJECT_JOBS: DASHBOARD_ROUTES.PROJECT_JOBS,
  PROJECT_JOB_DETAIL: DASHBOARD_ROUTES.PROJECT_JOB_DETAIL,
  
  // Settings routes
  USER_SETTINGS: DASHBOARD_ROUTES.USER_SETTINGS,
  HOSTING_SETTINGS: DASHBOARD_ROUTES.HOSTING_SETTINGS,
  HOSTING_ADD_CONNECTION: DASHBOARD_ROUTES.HOSTING_ADD_CONNECTION,
  HOSTING_CONFIGURE: DASHBOARD_ROUTES.HOSTING_CONFIGURE,
  HOSTING_GITHUB_ADD: DASHBOARD_ROUTES.HOSTING_GITHUB_ADD,
  HOSTING_GITHUB_CONFIGURE: DASHBOARD_ROUTES.HOSTING_GITHUB_CONFIGURE,
  HOSTING_GITHUB_CALLBACK: DASHBOARD_ROUTES.HOSTING_GITHUB_CALLBACK,
  HOSTING_GITLAB_ADD: DASHBOARD_ROUTES.HOSTING_GITLAB_ADD,
  HOSTING_GITLAB_CONFIGURE: DASHBOARD_ROUTES.HOSTING_GITLAB_CONFIGURE,
  HOSTING_SUCCESS: DASHBOARD_ROUTES.HOSTING_SUCCESS,
  AI_SETTINGS: DASHBOARD_ROUTES.AI_SETTINGS,
  WORKSPACE_SETTINGS: DASHBOARD_ROUTES.WORKSPACE_SETTINGS,
  TASK_SETTINGS: DASHBOARD_ROUTES.TASK_SETTINGS,
  QUALITY_GATES: DASHBOARD_ROUTES.QUALITY_GATES,
  BILLING_SETTINGS: DASHBOARD_ROUTES.BILLING_SETTINGS,
  
  // Integration routes
  BITBUCKET_CONNECT_HANDSHAKE: DASHBOARD_ROUTES.BITBUCKET_CONNECT_HANDSHAKE,
} as const;

// Re-export extractWorkspaceFromPath and isDashboardPath for backward compatibility
// (already exported above from utils, but keep inline versions for legacy code)

